In [9]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np


mat = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

print(mat)

for i in range(len(mat)):
    for j in range(len(mat)):
        print(mat[i][j])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9
