# All Combinations of a Matrix, Simple Testing Case

I want to compute all unique combinations of rows for a matrix. 

In [2]:
import itertools
import numpy as np

# Example matrix with 4 rows
matrix = np.array([
    [1, 2],
    [4, 4],
    [7, 8]])

unique_combos = []

# Get all unique combinations of rows
num_rows = len(matrix)
for r in range(1, num_rows + 1):  # r determines subset size
    for combo in itertools.combinations(matrix, r):
        print(np.array(combo))  # Each combo is a tuple of rows
        unique_combos.append(combo)
print(len(unique_combos))
print()
print()

# now, make each unique combination into an array with a length of 4. Each empty row should be all zeroes. put all arrays into a list.
padded_combos = []

for combo in unique_combos:
    padded_combo = np.zeros((3, matrix.shape[1]), dtype=int)
    for i, row in enumerate(combo):
        padded_combo[i] = row
    padded_combos.append(padded_combo)




[[1 2]]
[[4 4]]
[[7 8]]
[[1 2]
 [4 4]]
[[1 2]
 [7 8]]
[[4 4]
 [7 8]]
[[1 2]
 [4 4]
 [7 8]]
7




Compute number of combinations for a 4 row matrix using what I learned in STAT 661 to check that code works right. 

In [4]:
import math

four_choose_one = math.comb(4, 1)
four_choose_two = math.comb(4, 2)
four_choose_three = math.comb(4, 3)
four_choose_four = math.comb(4, 4)

combos_manual = four_choose_one + four_choose_two + four_choose_three + four_choose_four

print(combos_manual)

15
